autism/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
	path('', RedirectView.as_view(url='places/'), name='home'),
	path('users/', include('users.urls')),
	path('places/', include('places.urls')),
	path('admin/', admin.site.urls),
]

places/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import PlaceSearchView, PlaceView, RatingsView, RateView


app_name = 'places'

urlpatterns = [
	path('', RedirectView.as_view(url='search/')),
	path('search/', PlaceSearchView.as_view(), name='search'),
	path('<int:pk>/', PlaceView.as_view(), name='place'),
	path('<int:pk>/ratings/', RatingsView.as_view(), name='ratings'),
	path('<int:pk>/rate/', RateView.as_view(), name='rate'),
]

users/urls.py
from django.urls import path, include

from .views import RegisterView


# app_name = 'users'

urlpatterns = [
	path('register/', RegisterView.as_view(), name='register'),
	path('', include('django.contrib.auth.urls')),
]

places/models.py
from collections import namedtuple
from django.conf import settings
from django.db import models
from django.db.models import UniqueConstraint
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from django.db.models import Sum, Count
# from address.models import AddressField


minRating = 1
maxRating = 5
ratingValidators = [MinValueValidator(minRating), MaxValueValidator(maxRating)]


class Place(models.Model):
	name = models.TextField(max_length=280)
	address = models.TextField(max_length=280)
	sound_intensity_rating = models.FloatField(validators=ratingValidators, null=True, blank=True)
	light_intensity_rating = models.FloatField(validators=ratingValidators, null=True, blank=True)
	smell_intensity_rating = models.FloatField(validators=ratingValidators, null=True, blank=True)
	spaciousness_rating = models.FloatField(validators=ratingValidators, null=True, blank=True)
	total_rating = models.FloatField(validators=ratingValidators, null=True, blank=True)

	def update_ratings(self, subratings, total_rating):
		for sn in subratings._fields:
			try:
				v = getattr(subratings, sn)
				setattr(self, sn + '_rating', v)
			except AttributeError:
				pass
		self.total_rating = total_rating
		self.save()

	def get_absolute_url(self):
		return reverse('places:place', kwargs={'pk': self.pk})

	def __str__(self):
		return self.name


class Rating(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	place = models.ForeignKey(Place, on_delete=models.CASCADE)
	sound_intensity = models.IntegerField(validators=ratingValidators, null=True, blank=True)
	light_intensity = models.IntegerField(validators=ratingValidators, null=True, blank=True)
	smell_intensity = models.IntegerField(validators=ratingValidators, null=True, blank=True)
	spaciousness = models.IntegerField(validators=ratingValidators, null=True, blank=True)

	@staticmethod
	def get_subratings():
		return namedtuple('Subratings', [
			'sound_intensity',
			'light_intensity',
			'smell_intensity',
			'spaciousness',
		])

	class Meta:
		constraints = [
			UniqueConstraint(fields=['user', 'place'], name='rating_once')
		]


def update_place_scores(place):
	Subratings = Rating.get_subratings()

	scores = place.rating_set.aggregate(
		*([Sum(sn) for sn in Subratings._fields]
		+ [Count(sn) for sn in Subratings._fields])
	)

	scores = {k: (v if v is not None else 0) for k, v in scores.items()}

	total_sum = (scores['sound_intensity__sum'] + scores['light_intensity__sum']
		+ scores['smell_intensity__sum'] + scores['spaciousness__sum'])
	total_count = (scores['sound_intensity__count'] + scores['light_intensity__count']
		+ scores['smell_intensity__count'] + scores['spaciousness__count'])

	def avg(sum, count):
		return sum / count if count != 0 else None

	subratings = Subratings(
		sound_intensity = avg(scores['sound_intensity__sum'], scores['sound_intensity__count']),
		light_intensity = avg(scores['light_intensity__sum'], scores['light_intensity__count']),
		smell_intensity = avg(scores['smell_intensity__sum'], scores['smell_intensity__count']),
		spaciousness = avg(scores['spaciousness__sum'], scores['spaciousness__count']),
	)
	total_rating = avg(total_sum, total_count)
	place.update_ratings(subratings=subratings, total_rating=total_rating)

places/forms.py
from django import forms
# from crispy_forms.helper import FormHelper
# from crispy_forms.layout import Submit

from .models import Rating


# submit = Submit('', 'Search')
# submit.field_classes = 'btn btn-success'

class PlaceSearchForm(forms.Form):
	# helper = FormHelper()
	# helper.form_show_labels = False
	# helper.add_input(submit)
	# helper.disable_csrf = True
	q = forms.CharField(label='', max_length=80)


# class RatingWidget(forms.NumberInput):
	# template_name = 'places/rating_widget.html'

rating_widget = forms.NumberInput({
	'class': 'rating rating-loading',
	'step': '1',
	'data-theme': 'krajee-svg',
	'data-animate': 'false',
	'data-show-caption': 'false',
	'data-star-titles': 'false',
})

class RatingForm(forms.ModelForm):
	class Meta:
		model = Rating
		fields = ['sound_intensity', 'light_intensity', 'smell_intensity', 'spaciousness']
		widgets = {k: rating_widget for k in fields}

places/views.py
from django.urls import reverse
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.utils.translation import gettext as _
from django.db.models import Q

from base.views import CreateUpdateView, SearchView
from .models import Place, Rating, update_place_scores
from .forms import PlaceSearchForm, RatingForm


class PlaceSearchView(SearchView):
	form_class = PlaceSearchForm
	# model = Place
	ordering = '-total_rating'
	paginate_by = 6

	def get_queryset(self):
		if self.form.is_valid():
			query = self.form.cleaned_data['q']
			queryset = Place.objects.filter(
				Q(name__icontains=query)
			)
		else:
			queryset = Place.objects.none()
		self.queryset = queryset
		return super().get_queryset()


class PlaceView(DetailView):
	model = Place


class RatingsView(DetailView):
	model = Place
	template_name = 'places/ratings.html'


class RateView(LoginRequiredMixin, CreateUpdateView):
	model = Rating
	form_class = RatingForm
	template_name = 'places/rate.html'

	def do_get_object(self, queryset):
		user = self.request.user
		if not user.is_authenticated:
			raise Http404(_('No authenticated user.'))

		self.place_pk = self.kwargs.get('pk')
		try:
			self.place = Place.objects.get(pk=self.place_pk)
		except (Place.DoesNotExist, Place.MultipleObjectsReturned):
			raise Http404(_('No unique place found matching the query.'))

		if queryset is None:
			queryset = self.get_queryset()
		queryset = queryset.filter(user=user, place=self.place)

		try:
			obj = queryset.get()
		except (queryset.model.DoesNotExist):
			obj = None
		return obj

	def get_context_data(self, **kwargs):
		"""Insert the place into the context dict."""
		kwargs.setdefault('place', self.place)
		return super().get_context_data(**kwargs)

	def form_valid(self, form):
		if self.creating:
			form.instance.user = self.request.user
			form.instance.place = self.place
		response = super().form_valid(form)
		update_place_scores(self.place)
		return response

	def get_success_url(self):
		"""Return the URL to redirect to after processing a valid form."""
		return (reverse('places:rate', args=(self.place_pk,)) +
			('?q=%s' % self.request.GET['q'] if self.request.GET.get('q') else ''))

places/templates/places/place_detail.html
{% extends 'base.html' %}

{% block title %}{{ place.name }}{% endblock %}

{% block back %}
	<div id="back" class=><a href="{% url 'places:search' %}{% if request.GET.q %}?q={{ request.GET.q }}{% endif %}">
		<span><i class="bi bi-arrow-left"></i>{% block back_text %}Back{% endblock %}</span>
	</a></div>
{% endblock %}

{% block content %}
	<h2 class="mb-4">{{ place.name }}</h2>
	<h4 class="mb-4">{{ place.address }}</h4>
	{% include "places/rating_widget_disabled.html" with value=place.total_rating only %}
	<p><a href="{% url 'places:ratings' view.kwargs.pk %}{% if request.GET.q %}?q={{ request.GET.q }}{% endif %}">See detailed ratings</a></p>
	<p><a href="{% url 'places:rate' view.kwargs.pk %}{% if request.GET.q %}?q={{ request.GET.q }}{% endif %}">Rate it</a></p>
{% endblock %}

places/templates/places/place_list.html
{% if place_list %}
	<div>
		{% for place in place_list %}
			<article class="place">
				<a class="place-link" href="{% url 'places:place' place.pk %}{% if request.GET.q %}?q={{ request.GET.q }}{% endif %}">
					<div class="row no-gutters">
						<div class="col d-flex align-items-center place-name" style="text-align: left; min-width: 240px; min-height: 50px;">
							<span>{{ place.name }}</span>
						</div>
						<div class="col place-rating" style="margin-top: 6px; min-width: 190px;">
							{% include "places/rating_widget_disabled.html" with value=place.total_rating only %}
						</div>
					</div>
				</a>
			</article>
		{% endfor %}
	</div>

	{% if is_paginated %}
	<div class="row"></div>
	<hr>
	<nav aria-label="Places navigation">
		<ul class="pagination justify-content-center pagination-sm">
			{% if page_obj.has_previous %}
				<li class="page-item">
						<a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
				</li>
			{% else %}
				<li class="page-item disabled">
						<a class="page-link" href="#" tabindex="-1">Previous</a>
				</li>
			{% endif %}
			{% for i in paginator.page_range %}
				{% if page_obj.number == i %}
					<li class="page-item active">
						<a class="page-link" href="?page={{ i }}">
							<span>{{ i }}<span class="sr-only">(current)</span></span>
						</a>
					</li>
				{% else %}
					<li class="page-item">
						<a class="page-link" href="?page={{ i }}">
							<span>{{ i }}</span>
						</a>
					</li>
				{% endif %}
			{% endfor %}
			{% if page_obj.has_next %}
				<li class="page-item">
						<a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
				</li>
			{% else %}
				<li class="page-item disabled">
					<a class="page-link" href="#">Next</a>
				</li>
			{% endif %}
		</ul>
	</nav>
	{% endif %}
{% else %}
	<p>No places match the criteria.</p>
{% endif %}

places/templates/places/place_search.html
{% extends 'base.html' %}

{% block title %}Search{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
	<form method="get" class="search">
		{{ form }}
		<button type="submit" class="btn btn-success">Search</button>
	</form>
	{% if form.is_valid %}
		{% include 'places/place_list.html' %}
	{% endif %}
{% endblock %}

places/templates/places/rate.html
{% extends 'base.html' %}

{% block title %}{{ place.name }}{% endblock %}

{% block back %}
	<div id="back" class=><a href="{% url 'places:place' view.kwargs.pk %}{% if request.GET.q %}?q={{ request.GET.q }}{% endif %}">
		<span><i class="bi bi-arrow-left"></i>{% block back_text %}Back{% endblock %}</span>
	</a></div>
{% endblock %}


{% block content %}
	<h2 class="mb-4">{{ place.name }}</h2>
	<h4 class="mb-4">{{ place.address }}</h4>
	<form method="post">
		{% csrf_token %}
		{{ form }}
		<button type="submit" class="btn btn-success">Rate</button>
	</form>
{% endblock %}

places/templates/places/rating_widget.html
{% include "django/forms/widgets/number.html" %}

places/templates/places/rating_widget_disabled.html
<input value="{{ value|default_if_none:0 }}" class="rating rating-loading" disabled=""
	step="1" data-display-only="true" data-theme="krajee-svg" data-animate="false" data-show-caption="false" data-star-titles="false">

places/templates/places/ratings.html
{% extends 'base.html' %}

{% block title %}{{ place.name }}{% endblock %}

{% block back %}
	<div id="back" class=><a href="{% url 'places:place' view.kwargs.pk %}{% if request.GET.q %}?q={{ request.GET.q }}{% endif %}">
		<span><i class="bi bi-arrow-left"></i>{% block back_text %}Back{% endblock %}</span>
	</a></div>
{% endblock %}

{% block content %}
	<h2 class="mb-4">{{ place.name }}</h2>
	<h4 class="mb-4">{{ place.address }}</h4>
	<label for="id_sound_intensity">Sound intensity:</label>
	{% include "places/rating_widget_disabled.html" with value=place.sound_intensity_rating only %}
	<label for="id_light_intensity">Light intensity:</label>
	{% include "places/rating_widget_disabled.html" with value=place.light_intensity_rating only %}
	<label for="id_smell_intensity">Smell intensity:</label>
	{% include "places/rating_widget_disabled.html" with value=place.smell_intensity_rating only %}
	<label for="id_spaciousness">Spaciousness:</label>
	{% include "places/rating_widget_disabled.html" with value=place.spaciousness_rating only %}
	<p><a href="{% url 'places:rate' view.kwargs.pk %}{% if request.GET.q %}?q={{ request.GET.q }}{% endif %}">Rate it</a></p>
{% endblock %}